# Generated by Django 5.1.7 on 2025-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='images/players/cover')),
                ('country', models.CharField(max_length=100)),
                ('matches_for_country', models.PositiveSmallIntegerField()),
                ('matches_for_club', models.PositiveSmallIntegerField()),
                ('goals_for_country', models.PositiveSmallIntegerField()),
                ('goals_for_clubs', models.PositiveSmallIntegerField()),
                ('assist_for_country', models.PositiveSmallIntegerField()),
                ('assist_for_club', models.PositiveSmallIntegerField()),
                ('world_cup_matches', models.PositiveSmallIntegerField()),
                ('ballen_d_or', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
