# Generated by Django 5.1.7 on 2025-04-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_playercard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='assist_for_club',
            new_name='assist_for_clubs',
        ),
        migrations.RenameField(
            model_name='playercard',
            old_name='matches_for_club',
            new_name='matches_for_clubs',
        ),
    ]
