# Generated by Django 5.1.7 on 2025-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_assist_for_club_playercard_assist_for_clubs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='ballen_d_or',
            new_name='ballon_d_or',
        ),
    ]
